### ISSUE TITLE
Param Range only in whole Numbers

### ISSUE THREAD

**Issue by donkykong017** [Gab0/japonicus#100]
Is there a way to set the range of the Parameters only in whole numbers. i have a new strat to test that requires that for an array param. this could also be useful for SMA where no decimals are needed
thx
cheers
dk

**Comment by Gab0** [comment]
There are strategies that benefit from some parameters as floats.
 Would be a pain to differentiate those floats from ints that should be rounded on the GA. 
Of course we could round every param but would lose that floats.
 Gekko just don't care on getting floats. If you need ints on strat I would advise to round them inside the strategy, like Math.round(); 
cheers ^^

**Comment by donkykong017** [comment]
ok awesome. sry but i dont know that much abut python and js coding. thought it would be a setting in japonicus. thx for the answer i will look into the strat and try to edit it there.
;)
