### ISSUE TITLE
v0.54 Strategy Fails

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#104]
No final results after 800 Epochs and RBB Strategy Fails?
Never had an error like this prior to v0.54 update.

```

	======  EPOCH 799/800  ======
Locale9
first unevaluated: 4
2 individues removed due to equality
[2]
EPOCH 262	&2
Maximum profit 30.441	Average profit 28.829	
Minimum profit -13.754	Profit variation 7.827	
Population size 71	Max population size 67	
Avg trade number 27	Avg sharpe ratio 0.320	

Elder dies 0

Locale10
first unevaluated: 5
4 individues removed due to equality
[1]
EPOCH 237	&1
Maximum profit 15.938	Average profit 14.693	
Minimum profit -13.636	Profit variation 5.648	
Population size 86	Max population size 86	
Avg trade number 183	Avg sharpe ratio -0.438	

Elder dies 0

Epoch runs in 9.26 seconds;
Backend power [4.443584442138672]

4 selected;
1 selected;
Selecting 1+4 individues, random test;
Annual profit -23.524%
Testing Strategy of Locale9 @ EPOCH 263:

Strategy Fails.
4 selected;
1 selected;
Selecting 1+4 individues, random test;
Annual profit 13.115%
Testing Strategy of Locale10 @ EPOCH 238:

Strategy Fails.
[<datasetOperations.CandlestickDataset object at 0x7fbb38863cc0>, None]
4 selected;
1 selected;
Selecting 1+4 individues, random test;
Annual profit -33.267%
Testing Strategy of Locale9 @ EPOCH 263:

Strategy Fails.
4 selected;
1 selected;
Selecting 1+4 individues, random test;
Annual profit -6.190%
Testing Strategy of Locale10 @ EPOCH 238:

Strategy Fails.

		.RUN ENDS.
```

**Comment by BradT7** [comment]
Also getting this error, when my dataset is larger than 60 or 90 days

```
Fatal: deltaDays on Settings.py set to a value bigger than current dataset.
 Edit Settings file to fit your chosen candlestick data.
```

**Comment by BradT7** [comment]
Issue localized to one separate gekko/japonicus folder, error did not happen with a second gekko/japonicus folder I was backtesting on. I've deleted that folder and started fresh again, hopefully that will resolve.

**Comment by Gab0** [comment]
Hey, strat failed becaus of score below zero. japonicus will protect u against dangerous parameters unless you change genconf.showIndividualEvaluationInfo ;)

**Comment by BradT7** [comment]
What's odd is it was the same parameters as a successful run in another gekko/japonicus folder, just different dataset with different date ranges, it was actually the bull date range that this failure happened too, and the bear date range completed normally. I'll test again tonight with the fresh install. :)

**Comment by BradT7** [comment]
Hey Gab, I've had negative results still spit out successful results in a manual gekko backtest. Just take a look at some past logs I've sent.  Perhaps it could still display the final result, even if it's negative.  I just hate to see it do 800 epochs and I'm left with nothing.  The problem with enabling that setting you mentioned, is I imagine I would need to look through 800 results to try and find the most favourable result, even if negative.  Thanks for all work!
