### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#108]
Hi,

I wonder were the output now goes after a succesfull run?
Do I need to create a output directory if it is not there?
I can only look at the log files no to see results...

in the settings file it says:
```

        'Global': {
            'gekkoPath': HOME+'/gekko',
            'configFilename': 'config-hk.js', # example-config.js
            'save_dir': "output",
            'log_name': 'evolution_gen.csv',
```

But i do not see any `output` directory...

**Comment by Gab0** [comment]
Savedir and output dir are deprecated, results are now at `japonicus/logs`. The mkdir is automated ;}

**Comment by hugokoopmans** [comment]
ok thx the output dit is still in settings though but thats a minor issue
