### ISSUE TITLE
Feature request : show daterange on backtests and evaluations

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#109]
It would be nice to add the daterange in the log on which a strat is tested and or evaluated. This way we better understand how the backtests are done.

**Comment by donkykong017** [comment]
this is already in the log at the beginning.

> evolution candlestick dataset 2017-10-18 10:10:00 to 2018-03-17 10:10:00
LTC/BTC @gdax


evaluation candlestick dataset 2017-08-04 13:37:00 to 2018-02-20 13:37:00
BTC/EUR @gdax

**Comment by hugokoopmans** [comment]
no i dont think so, that is the available candles in the database not the evaluation periods used for testing as far as i know

**Comment by hugokoopmans** [comment]
in the log directory the csv files of the locale 1 and 2 the dateRange column is empty so also not there...

**Comment by donkykong017** [comment]
this is the whole dataset the strat is tested on in small ranges of `deltaDays` and evaluated every evaluation period on the whole set

**Comment by Gab0** [comment]
@hugokoopmans @donkykong017 Yeah that info that appears on console is all the range for imported datasets. Each locale has its own daterange to do every backtest, and that info should be on next update today..
