### ISSUE TITLE
How to set the dateRange for evoluation ?

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#110]
My usecase:

I want to set the timespan used for evoluation and evaluation explicitly.
I have minute candles in my database from 1 januari 2018 BUT i only want to use the last 30 days in my GA, how to do this?

This is my settings.py 

```
    'dataset' : {
        # -- Gekko Dataset Settings
        # leave the ! on the ignored entry as convenient;
        '!dataset_source': None,
         # dataset_source can be set to None so it searches from any source;
        'dataset_source': { # in case of specifying exchange-currency-asset, rename this removing the '!', and del the original key above.
            "exchange": "kraken",
            "currency": 'EUR',
            "asset": 'ETH',
        }, 
```

Can I add a daterange here? How?

thx

**Comment by hugokoopmans** [comment]
or can i use dataset_span setting for this?
I just want to make sure I can control on which part of the dataset I run the ga...

**Comment by Gab0** [comment]
Evoluation_dataset? haa `dataset_span` is for evolution, `eval_dataset_span` is for evaluation dataset. To do what you want the value is 30.
cheers!
