### ISSUE TITLE
web error in new version

### ISSUE THREAD

**Issue by donkykong017** [Gab0/japonicus#112]
hey i got this in the newest version. can't seem to solve it myself

> `File "/home/david/gekko/japonicus/web.py", line 43, in update_graph
>     statisticNames = { k: sNa.get(k,0) + sNb.get(k,0) for k in set(sNa) | set(sNb) }
>   File "/home/david/gekko/japonicus/web.py", line 43, in <dictcomp>
>     statisticNames = { k: sNa.get(k,0) + sNb.get(k,0) for k in set(sNa) | set(sNb) }
> TypeError: must be str, not int
> `
not using the -w flag solves it. has something to to with the drawing of the web graphs
also i think it was said before. there is a typo in web.py in line 42

> `  File "/home/david/gekko/japonicus/web.py", line 42, in update_graph
>     sNb = periodicStatistcsNames
> NameError: name 'periodicStatistcsNames' is not defined
> `

periodicStatisticsNames

edit:

i get this error now after few epochs.

> `======  EPOCH 73/800  ======
> Locale2
> first unevaluated: 12
> 5 individues removed due to equality
> [7]
> EPOCH 73	&7
> Maximum profit 218.025	Average profit 193.550	
> Minimum profit -338.056	Profit variation 101.486	
> Population size 98	Max population size 90	
> Avg trade number 288.286	Avg sharpe ratio 0.405	
> 
> Elder dies 0
> 
> Locale3
> first unevaluated: 30
> 0 individues removed due to equality
> [30]
> Error: config failure
> http://localhost:3000/api/backtest
> {'gekkoConfig': {'debug': True, 'info': True, 'watch': {'exchange': 'gdax', 'currency': 'EUR', 'asset': 'BTC'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'RSI_BULL_BEAR_ADX', 'candleSize': 15, 'historySize': 10}, 'RSI_BULL_BEAR_ADX': {'BULL_RSI_low': 54.90909090909091, 'BULL_MOD_low': -5.1060606060606055, 'BULL_MOD_high': 5.318181818181818, 'BEAR_RSI_high': 34.09090909090909, 'SMA_long': 872.7272727272727, 'ADX': 1.9818181818181817, 'BULL_RSI': 7.7727272727272725, 'BULL_RSI_high': 83.39393939393939, 'BEAR_RSI_low': 24.87878787878788, 'SMA_short': 62.72727272727273, 'BEAR_MOD_high': 16.59090909090909, 'ADX_low': 34.621212121212125, 'BEAR_RSI': 18.18181818181818, 'ADX_high': 56.63636363636364, 'BEAR_MOD_low': -4.416666666666666}, 'backtest': {'daterange': {'from': '2017-10-11 13:07:43', 'to': '2018-01-09 13:07:43'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/home/david/gekko/japonicus/evolution_generations.py", line 55, in bEvaluate
>     genconf, Database, DateRange, phenotype, gekkoUrl
>   File "/home/david/gekko/japonicus/evaluation/gekko/backtest.py", line 68, in Evaluate
>     for DR in DateRange
>   File "/home/david/gekko/japonicus/evaluation/gekko/backtest.py", line 68, in <listcomp>
>     for DR in DateRange
>   File "/home/david/gekko/japonicus/evaluation/gekko/backtest.py", line 40, in runBacktest
>     result = httpPost(url, gekko_config)
>   File "/home/david/gekko/japonicus/evaluation/gekko/API.py", line 24, in httpPost
>     raise e
>   File "/home/david/gekko/japonicus/evaluation/gekko/API.py", line 16, in httpPost
>     Response = json.loads(Request.text)
>   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "japonicus.py", line 154, in <module>
>     launchJaponicus()
>   File "japonicus.py", line 139, in launchJaponicus
>     TargetParameters, GenerationMethod, EvaluationMode, web=web_server
>   File "/home/david/gekko/japonicus/evolution_generations.py", line 170, in gekko_generations
>     World.runEPOCH()
>   File "/home/david/gekko/japonicus/promoterz/sequence/parallel_world.py", line 13, in world_EPOCH
>     LOCALE.run()
>   File "/home/david/gekko/japonicus/promoterz/locale.py", line 39, in run
>     self.loop(self.World, self)
>   File "/home/david/gekko/japonicus/promoterz/sequence/standard_loop.py", line 34, in standard_loop
>     locale
>   File "/home/david/gekko/japonicus/promoterz/evaluationPool.py", line 73, in evaluatePopulation
>     results[A] = results[A].get(timeout=timeout)
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/david/gekko/japonicus/promoterz/evaluationPool.py", line 39, in evaluateBackend
>     fitnesses = P.starmap(self.EvaluationTool, Q)
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> `

**Comment by Gab0** [comment]
Some bugs on web.py... solved. Thanks!
