### ISSUE TITLE
Current parameters fails

### ISSUE THREAD

**Issue by Profex86** [Gab0/japonicus#114]
Tinkerboard
Gekko v0.5.13

Hallo, i start with

python3.6 /opt/gekko/japonicus/japonicus.py -g --strat RSI

when the algorithm is done...

Testing Strategy of Locale15 @ EPOCH 136:

Testing monthly profit -10.268 	 nbTrades: 1.0
Testing monthly profit -3.862 	 nbTrades: 4.0
Testing monthly profit -1.949 	 nbTrades: 3.0
Testing monthly profit -9.677 	 nbTrades: 3.0
Testing monthly profit -0.456 	 nbTrades: 5.0
Testing monthly profit -4.399 	 nbTrades: 5.0
Testing monthly profit -2.136 	 nbTrades: 4.0
Testing monthly profit -8.352 	 nbTrades: 3.0
Testing monthly profit -3.961 	 nbTrades: 4.0
Testing monthly profit 1.339 	 nbTrades: 5.0
Testing monthly profit 2.906 	 nbTrades: 5.0
Testing monthly profit -7.097 	 nbTrades: 3.0

Relative profit on evolution dataset: -47.913
Current parameters fails. <----? what is wrong?

		.RUN ENDS.

**Comment by Gab0** [comment]
Hey, that means it lost money on the simulation.. Algo flagged that single parameter set as not worthy of further analysis. This is standard with sample strategies such as RSI.

**Comment by Profex86** [comment]
and what about this?
Testing Strategy of Locale8 @ EPOCH 13:

Testing monthly profit -0.145 	 nbTrades: 1.0
Testing monthly profit 2.531 	 nbTrades: 1.0
Testing monthly profit -0.444 	 nbTrades: 1.0
Testing monthly profit -6.309 	 nbTrades: 1.0
Testing monthly profit 8.752 	 nbTrades: 3.0
Testing monthly profit -1.182 	 nbTrades: 3.0
Testing monthly profit -9.714 	 nbTrades: 1.0
Testing monthly profit 11.657 	 nbTrades: 1.0
Testing monthly profit 8.354 	 nbTrades: 3.0
Testing monthly profit 8.866 	 nbTrades: 1.0
Testing monthly profit -0.785 	 nbTrades: 1.0
Testing monthly profit 7.192 	 nbTrades: 1.0

Relative profit on evolution dataset: 28.772
Current parameters fails.
Skipping further tests on current parameters.

**Comment by Gab0** [comment]
check Settings.py, there an option with an indentifiable name.
