### ISSUE TITLE
Genetic vs Bayesian strategy errors

### ISSUE THREAD

**Issue by phbprogramming** [Gab0/japonicus#117]
Hello there! I have some questions about the genetic algorithm flag that I wasn't able to find in the wiki. I'm able to run program using the Bayesian optimization without a hitch, but for some reason, whenever I run the GA, it is telling me that all of my epoch runs take zero seconds. If I need to submit any output, I can do that. 

Also, what is the purpose of the settings file referencing my config.js? Is the program not just running my selected strategy on the specified currency pair? As of right now, I've edited the settings.py with my desired currency pair, and I've put in the strat settings in configStrategies.py. Is there something I might have missed? Much appreciated.

**Comment by Gab0** [comment]
Hey, is your issue like #116? There is a duct tape solution on the topic.
If its not, please paste the error here.. I'm working on a update right now.
cheers!

**Comment by Gab0** [comment]
hey, have you tried to run a few different strategies? Anyway, provide a full log of the operation for me to check it.
cheers!

**Comment by phbprogramming** [comment]
Hey, so I've run the program again, and here's what I'm getting:

`Evolving devStrat strategy;

evaluated parameters ranges:
short                         (7.0, 13.0)

long                          (14.0, 26.0)

signal                        (6.3, 11.7)

historicalRange               (9.8, 18.2)

overBought                    (95, 75)

overSold                      (25, 5)

stopLoss                      (56.0, 104.0)



evolution candlestick dataset 2017-05-01 00:19:00 to 2018-02-28 23:56:00
USDT/USD @kraken



evaluation candlestick dataset 2017-07-01 00:39:00 to 2018-03-10 21:39:00
XRP/USD @kraken

	======  EPOCH 0/800  ======
Locale1
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 17.192, 'long': 15.56, 'overBought': 81.6, 'overSold': 19.8, 'short': 10.6, 'signal': 6.3, 'stopLoss': 93.92}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 17.108, 'long': 17.6, 'overBought': 85.2, 'overSold': 17.6, 'short': 12.34, 'signal': 9.809999999999999, 'stopLoss': 71.36}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 16.1, 'long': 14.96, 'overBought': 79.4, 'overSold': 10.2, 'short': 11.74, 'signal': 7.002, 'stopLoss': 83.36}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 10.892000000000001, 'long': 17.0, 'overBought': 90.8, 'overSold': 21.4, 'short': 9.34, 'signal': 6.678, 'stopLoss': 78.08}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 12.656, 'long': 25.4, 'overBought': 84.6, 'overSold': 19.4, 'short': 10.66, 'signal': 7.433999999999999, 'stopLoss': 59.84}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 13.496, 'long': 19.28, 'overBought': 91.0, 'overSold': 9.2, 'short': 12.58, 'signal': 9.648, 'stopLoss': 88.16}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 14.084, 'long': 22.64, 'overBought': 82.2, 'overSold': 23.2, 'short': 11.26, 'signal': 6.84, 'stopLoss': 70.4}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 17.444, 'long': 16.64, 'overBought': 85.4, 'overSold': 14.399999999999999, 'short': 10.54, 'signal': 9.972, 'stopLoss': 85.28}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 10.724, 'long': 20.240000000000002, 'overBought': 84.2, 'overSold': 17.6, 'short': 9.94, 'signal': 8.73, 'stopLoss': 74.72}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 16.352, 'long': 15.56, 'overBought': 93.8, 'overSold': 7.599999999999998, 'short': 9.64, 'signal': 10.079999999999998, 'stopLoss': 103.03999999999999}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 15.176, 'long': 20.96, 'overBought': 85.8, 'overSold': 18.4, 'short': 8.26, 'signal': 7.002, 'stopLoss': 90.08}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 16.94, 'long': 17.12, 'overBought': 93.8, 'overSold': 13.799999999999999, 'short': 12.399999999999999, 'signal': 7.38, 'stopLoss': 62.72}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 12.824, 'long': 20.240000000000002, 'overBought': 92.4, 'overSold': 12.0, 'short': 11.02, 'signal': 7.056, 'stopLoss': 57.44}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 15.176, 'long': 16.52, 'overBought': 82.4, 'overSold': 11.0, 'short': 7.36, 'signal': 6.786, 'stopLoss': 96.32}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 13.664, 'long': 15.56, 'overBought': 86.8, 'overSold': 14.2, 'short': 11.44, 'signal': 10.404, 'stopLoss': 90.56}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 12.572000000000001, 'long': 17.72, 'overBought': 94.8, 'overSold': 20.4, 'short': 11.379999999999999, 'signal': 9.0, 'stopLoss': 78.08}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 15.092, 'long': 22.759999999999998, 'overBought': 94.2, 'overSold': 8.599999999999998, 'short': 9.64, 'signal': 11.267999999999999, 'stopLoss': 78.56}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 13.076, 'long': 23.48, 'overBought': 87.0, 'overSold': 6.0, 'short': 8.98, 'signal': 8.405999999999999, 'stopLoss': 57.44}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 17.528, 'long': 18.2, 'overBought': 82.2, 'overSold': 10.799999999999999, 'short': 8.62, 'signal': 9.54, 'stopLoss': 100.64}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 12.74, 'long': 17.0, 'overBought': 83.2, 'overSold': 24.4, 'short': 9.94, 'signal': 10.296, 'stopLoss': 96.8}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 14.168, 'long': 15.08, 'overBought': 91.6, 'overSold': 14.399999999999999, 'short': 12.879999999999999, 'signal': 8.081999999999999, 'stopLoss': 96.8}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 9.8, 'long': 15.32, 'overBought': 80.0, 'overSold': 16.2, 'short': 7.9, 'signal': 9.161999999999999, 'stopLoss': 68.48}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 13.412, 'long': 14.72, 'overBought': 87.6, 'overSold': 20.4, 'short': 11.620000000000001, 'signal': 9.161999999999999, 'stopLoss': 90.56}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 11.228000000000002, 'long': 15.56, 'overBought': 81.2, 'overSold': 17.2, 'short': 7.72, 'signal': 10.187999999999999, 'stopLoss': 81.92}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 10.388, 'long': 15.8, 'overBought': 83.6, 'overSold': 22.8, 'short': 12.219999999999999, 'signal': 9.485999999999999, 'stopLoss': 64.64}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 12.656, 'long': 23.36, 'overBought': 90.8, 'overSold': 21.4, 'short': 11.26, 'signal': 8.622, 'stopLoss': 82.4}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 9.8, 'long': 16.04, 'overBought': 81.2, 'overSold': 10.0, 'short': 10.24, 'signal': 7.973999999999999, 'stopLoss': 62.72}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 13.664, 'long': 22.759999999999998, 'overBought': 87.8, 'overSold': 9.6, 'short': 11.8, 'signal': 9.863999999999999, 'stopLoss': 56.0}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 15.008, 'long': 20.12, 'overBought': 94.0, 'overSold': 17.4, 'short': 8.02, 'signal': 11.483999999999998, 'stopLoss': 95.84}
--destroying invalid citizen--
	( invalid values on 17.500000 overSold 6.500000)

{'historicalRange': 10.304, 'long': 25.64, 'overBought': 93.2, 'overSold': 8.2, 'short': 12.399999999999999, 'signal': 8.352, 'stopLoss': 64.16}
first unevaluated: 0
0 individues removed due to equality`

And then a lot of this:

`Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 2/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 3/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 4/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 5/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 6/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 7/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 8/800  ======
Locale2
Epoch runs in 0.00 seconds;

	======  EPOCH 9/800  ======
Locale2
Epoch runs in 0.00 seconds;
`

Is there a full installation and setup somewhere? I'm thinking this just has to be an issue with me not correctly setting everything up, and editing the correct files.

**Comment by Gab0** [comment]
Hey, did you manually set up parameter ranges?

overBought                    (95, 75)

overSold                      (25, 5)

this means a minimum of 25, maximum of 5 so its clearly impossible... I will put a failsafe against this surely. If this ranges were generated automatically, we got bugz... please tell us the story x]
cheers!

**Comment by Gab0** [comment]
Yeah, thats what you need to start up...
you can also add .toml configs for strategies in `japonicus/strategy_parameters` instead of editing configStrategies.py..
