### ISSUE TITLE
v0.58 issues

### ISSUE THREAD

**Issue by jthope** [Gab0/japonicus#119]
I am getting the following issues with the latest commits:
![image](https://user-images.githubusercontent.com/114626/38528238-acac6062-3c2c-11e8-8fad-0a8feb178a71.png)

I removed this import from statistics.py and evolution_generations.py as it did not appear to be used.

Next issue after trying to run:
![image](https://user-images.githubusercontent.com/114626/38528347-2dd989e4-3c2d-11e8-8513-b8004832bbf0.png)

Figured, maybe that is not used yet, so I commented out, however, it is being used:
![image](https://user-images.githubusercontent.com/114626/38528303-02cc575e-3c2d-11e8-84ef-8758e865b416.png)

Any ideas?

**Comment by Gab0** [comment]
Oh sorry, didn't add those new files to repo... this is solved ^^
