### ISSUE TITLE
Settings & Results terms explanation

### ISSUE THREAD

**Issue by nmikaty** [Gab0/japonicus#120]
Hi @Gab0 ,

Could you explain quickly what the following terms are referring to please?:

In settings:
- proofSize
- GeneSize 
- Density 

In results:
- Testing Strategy of Locale4 @ EPOCH 11
> there was no Locale4 at epoch 11, and no evaluation running at epoch 11, so I'm not sure how to interpret this. This doesn't seem to be an age either since it sometimes shows epochs over 100 (my locales are supposed to explode after 100).
- Testing monthly profit 102.171   nbTrades: 51.0
> Does this test happen over a month randomly inside the date range? Or does the first one starts at the beginning and the second follows?
- Backend power
- EPOCH 121       &7 
> What is &7?

Thanks in advance!
I'm having a lot of fun with your code!

**Comment by nmikaty** [comment]
- Testing Strategy of Locale4 @ EPOCH 11
>About this one, going through the logs for each locale, I found that they do not surely explode at 100 epochs.
>So it would make sense that EPOCH 11 is the age of the locale at the time of the test.

**Comment by Gab0** [comment]
@nmikaty yeah 11 is the age of the locale... maybe should we call it LEPOCH? :c
The monthly profit is no more monthly... its deltaDays in length.. so yeah I will change that.
& indicates the number of evaluations for that locale on that EPOCH..
About the settings, the info is really missing so it will be at Settings.py on the next update.
cheers!

**Comment by Gab0** [comment]
update is online.. check `Settings.py`.

**Comment by nmikaty** [comment]
Thanks @Gab0 it's much clearer now 👍
