### ISSUE TITLE
requirements.txt requires exakt version numbers which fail on pip install

### ISSUE THREAD

**Issue by simpsus** [Gab0/japonicus#125]
the title. I would prefer a running install and version problems afterwards.

**Comment by Gab0** [comment]
Are you using pip3 to install those? Is your pip3 upgraded `sudo pip3 install --upgrade pip`?Anyway if it continues to give error you can just delete the `==3.4.1` thing for failing package on requirements.txt XD

**Comment by simpsus** [comment]
pip3 and python3, yes.
Removing the version requirements work.
I just thought as the available versions are much newer than the ones required, there is only negative value in requiring the level
