### ISSUE TITLE
no grapg shown with -w option

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#129]
Hi,

Great work so far, I am trying out the -w option to view the webpage.

It starts the web page and shows
![image](https://user-images.githubusercontent.com/2493853/39071931-22188cd0-44e9-11e8-80ea-9443d2b4c9d9.png)

I am on linux mint 18.3

It seems the graphical component is not actually updated

CLI output: 

python japonicus.py -g -w --strat RSI_BULL_BEAR
WEBSERVER MODE
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
	GEKKO
        ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
        ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
        ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
   ██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
   ╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
    ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.58

The profits reported here depends on backtest interpreter function; 
	interpreter v3: 
if <backtest profit> > 0: <shown profit> = <backtest profit> - <market profit> 
else <shown profit> = <backtest profit> 
japonicus.py -g -w --strat RSI_BULL_BEAR
Evolving RSI_BULL_BEAR strategy;

evaluated parameters ranges:
SMA_long                      (750.0, 1250.0)

SMA_short                     (37.5, 62.5)

BULL_RSI                      (7.5, 12.5)

BULL_RSI_high                 (60.0, 100.0)

BULL_RSI_low                  (45.0, 75.0)

BEAR_RSI                      (11.25, 18.75)

BEAR_RSI_high                 (37.5, 62.5)

BEAR_RSI_low                  (15.0, 25.0)

evolution candlestick dataset 2018-03-20 05:06:00 to 2018-04-19 05:06:00
ETH/EUR @kraken

evolution candlestick dataset 2018-03-20 05:06:00 to 2018-04-19 05:06:00
ETH/EUR @kraken

evaluation candlestick dataset 2018-02-23 13:20:00 to 2018-03-15 13:20:00
XBT/USD @kraken

	======  EPOCH 0/50  ======
Locale1
first unevaluated: 250
0 individues removed due to equality
[250]
127.0.0.1 - - [20/Apr/2018 22:09:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:40] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:40] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:40] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:40] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:09:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:15] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:15] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:30] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2018 22:10:30] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by Gab0** [comment]
Hey, a pop size of 250 is a bit too much XDD
The graphic should appear one locale one has completed all of its evaluations. Should take long with 250 inds.

**Comment by xaviermiss** [comment]
OK. Thank you Gab0 !
