### ISSUE TITLE
Some small requests

### ISSUE THREAD

**Issue by xFFFFF** [Gab0/japonicus#135]
I have a few requests, you may like gab0.

- maximum number of trades. this is important because NN strategies like to make a profit on a huge amount of trades from 0.001%. In live such trades are unprofitable
- min and max exposed duration - like above
- saving all results to CSV or even JSON. This will allow for better calibration of parameters when we know the results better.
- dont reject parameters which generate loss. With some datasets you can not have a profit, then it is better to have the best possible loss.

My japonicus finds settings after several epoch, for the next 200 still the same parameters are the best. That's good? Should I change something in the settings?
Examples of parameters:
```
"NN_HMA": {
"threshold_buy_bear": (3,12),
"threshold_buy_bull": (1.2,3),
"threshold_sell_bear": (-1,-0.8),
"threshold_sell_bull": (-2,-0.8),
"NN_HMA_Length": (5,40),
"maFast": (20,95),
"maSlow": (200,800),
"price_buffer_len": (20,150)
},
```

**Comment by xFFFFF** [comment]
'showFailedStrategies': True 
Did you write about this setting? If it's True then the negative results will also be taken in evolution? Im using v1 cos im looking stable strategy to live trade. Not need 200% profit in month. I need havent loss on all market condition :)

I understand that there may be a problem with filters. I have no idea how to solve it. What I meant was that I want a safe strategy, which I buy only when the trade is profitable in the next few hours and sells. In this way, I will be able to minimize the chance of falling into a dump. I would like to reject the settings that earn money for a hodl in a given dataset.

I meant writing all results and their values (relative profit etc) together with the generated strategy settings to external file. It's about something like csv file on my repo with strategies generated by BacktestTool. I would like to preview what the Japonicus does, what combinations it chooses and learn a better configuration. At the moment I see only the best result.

I played some settings
'parameter_spread' : 15,
  'NBBESTINDS': 3,
 'NBADDITIONALINDS': 5,
Obtains more unique settings with such values.

One more question: how does multiple dataset work? What does the epoch choose a different dataset for locales? Does every epoch test all datasets in each of the locales?

**Comment by Gab0** [comment]
Hey, 'v1' has nothing to do with stability I think... 'v1' is the simplest mode that returns actual backtest results. For stability 'v3' should be better suited.

Nice... this exposure thing is in what I'm currently working here... to avoid too long or too short exposures. coming soon..

Oh I see... a full evolution log. Man that would be 5MB in size. This would involve a major architecture rewrite that can't be done now :c But if you want more results to be logged just go NBADDITIONALINDS to 20 or something... would be like what you want.

One locale gets one part of a dataset chosen at random at its creation, and holds it till the end.

So the exposure thing is coming on the next update, do you have any suggestions on how to implement it the best way? Can be like a filter that eliminates a parameter that exposes for too long or like an additional fitness score that is higher when average exposure is near the length in candles that was chosen, I'm looking at it.
cheers!

**Comment by xFFFFF** [comment]
Thanks Caval! I didnt seen score before. Its working nice. What values of sharpe and profit you recommend for my logic? I would have week without trades instead loss.

**Comment by xFFFFF** [comment]
You are push new version... without these features :(

**Comment by Gab0** [comment]
@xFFFFF  `You are push new version... without these features :(`
haaa grow up man 

XDD jkjk new version is online feat. exposure filters.
cheers!

**Comment by xFFFFF** [comment]
Nice that You try but You forgot about max trades. Its very important for me. I have strats which generate 1700 trades on 2 week period. This settings would make my live better.

I will grow up, but tomorrow :)

**Comment by xFFFFF** [comment]
Thanks, master! You are great!
