### ISSUE TITLE
japonicus_halt! :)

### ISSUE THREAD

**Issue by xFFFFF** [Gab0/japonicus#139]
```
python3.6 japonicus.py -egc --strat RSI_Bull_Bear_Adx_M1
Traceback (most recent call last):
  File "japonicus.py", line 3, in <module>
    import japonicus_halt
ModuleNotFoundError: No module named 'japonicus_halt'
```
I would try what is benchmark and get this error...

**Comment by xFFFFF** [comment]
new config files in logs rox. 
now I can write something to import them all to backtestool :)

toml is more user friendly, less commas, quotes and others :)

**Comment by Gab0** [comment]
lool forgot to add `japonicus_halt.py` file to repo ^^
No time to do a couple runs so I could see those repeated results... fair to not repeat those toml files...
submitting a fix to this soon.
cheers!

**Comment by xFFFFF** [comment]
These results are not always identical. Different parameter values from a given locale and epoch are added to the file. I do not know why, he does not try to understand how the Japonicus works. :) I have: `'evaluateSettingsPeriodically': 1`
Maybe it displays and saves the best result every time this result is corrected?

**Comment by Gab0** [comment]
@xFFFFF The default for this parameter is 50 which will pause the GA to evaluate parameters every 50 epoches! 1 is kinda small interval.
About result replacement: I think its the way you described... if some ind on same evaluation break gets better score than a previous.. it replaces the prev. 
cheers!

**Comment by xFFFFF** [comment]
>The default for this parameter is 50 which will pause the GA to evaluate parameters every 50 epoches! 1 is kinda small interval.
You mean this settings slow down system performance? I must see what this devil does because often have wrong parameters for strategy and generate a lot of trades. 1700 trades per 2 weeks is insane :) Its why i please You about new features from my another issue.
