### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by Kris191** [Gab0/japonicus#144]
Hi all,

Can anyone help with the below error? Iiiii'm tryng to backtest thee nuralenet strat and get this error when i try to run `it.`
```
Evaluation dataset not found.
Traceback (most recent call last):
  File "japonicus.py", line 176, in <module>
    launchJaponicus(parser)
  File "japonicus.py", line 161, in launchJaponicus
    EvaluationMode, settings, options, web=web_server
  File "/root/gekko/japonicus/evolution_generations.py", line 139, in gekko_generations
    TargetParameters, genconf.parameter_spread
  File "/root/gekko/japonicus/promoterz/parameterOperations.py", line 41, in parameterValuesToRangeOfValues
    spread_change = Spread * P / 200
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```
Strangely it runs fine in Gekko Ui backtesting, can someone help please?

**Comment by Gab0** [comment]
Hey, please paste neuralnet TOML settings here. I guess there some strange parameter there like 'false' or something, but we can see what we do. At first, try to change bools to 1 or 0. cheers!

**Comment by Kris191** [comment]
HI Gab0, 

will post later but you are right false is in the toml.

Thanks

Kris

**Comment by Kris191** [comment]
i have it working now, it must be the false text in the toml. I'm going to close as i no longer have the issue.

Thanks
