### ISSUE TITLE
BackTest with neuralnet

### ISSUE THREAD

**Issue by desps-iscteiulpt** [Gab0/japonicus#146]
Hey great software btw,
   Trying to work with https://github.com/zschro/gekko-neuralnet but without success, could you help me a bit ?

~/gekkojap/japonicus$ python3.6 japonicus.py -g --strat neuralnet
	GEKKO
        ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
        ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
        ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
   ██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
   ╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
    ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.70

The profits reported here depends on backtest interpreter function; 
	interpreter v3: 
if <backtest profit> > 0: <shown profit> = <backtest profit> - <market profit> 
else <shown profit> = <backtest profit> 
japonicus.py -g --strat neuralnet
Evolving neuralnet strategy;

evaluated parameters ranges:
threshold_buy                 [0.1, 3.5]

threshold_sell                [-3.5, -0.1]

learning_rate                 [0.01, 0.25]

decay                         [0.01, 0.1]

hodl_threshold                [0.8, 1.0]

price_buffer_len              [30, 300]

evolution candlestick dataset 2018-01-01 00:42:00 to 2018-05-29 02:42:00
CMT/ETH @binance

evolution candlestick dataset 2018-01-01 00:00:00 to 2018-05-30 02:21:00
ADX/ETH @binance

evaluation candlestick dataset 2018-01-01 00:00:00 to 2018-05-29 01:34:00
ADA/ETH @binance

	======  EPOCH 0/800  ======
Locale1
first unevaluated: 30
0 individues removed due to equality
[30]
EPOCH 0	&30
Maximum profit -0.038    Average profit -0.038    
Minimum profit -0.038    Profit variation 0       
Population size 30       Max population size 30   
Avg trade number 0       Avg sharpe ratio 0       
Avg exposure time 0      

my strategy_parameters/neuralnet.toml

threshold_buy = [0.10, 3.50]
threshold_sell = [-3.50, -0.10]
learning_rate = [0.01, 0.25]
decay = [0.01, 0.10]
hodl_threshold = [0.80 , 1.00]
price_buffer_len = [30, 300]

my configStrategies.py
...
"neuralnet": {
        "threshold_buy": (0.10, 3.50),
        "threshold_sell": (-3.50, -0.10),
        "learning_rate": (0.01, 0.25),
        "decay": (0.01, 0.10),
        "hodl_threshold": (0.80 , 1.00),
        "price_buffer_len": (30, 300)
}

and my gekko config

//neuralnet settings
config.neuralnet = {
  "threshold_buy": 0.125,
  "threshold_sell": -0.125,
  "method": "adadelta",
  "learning_rate": 0.01,
  "momentum": 0.1,
  "decay": 0.01,
  "stoploss_enabled": true,
  "stoploss_threshold": 0.85,
  "hodl_threshold": 1,
  "price_buffer_len": 100,
  "min_predictions": 1000
};

in gekko backtest that config works fine, so I assume its some configuration error I made in japonicus, it's not doing any trades. And how can I select only 1 Local to backtest ? like only ETH-TRX

thanks!

**Comment by desps-iscteiulpt** [comment]
With NNv2 no issues running will close thread.

**Comment by CryptoCoeus** [comment]
Hi, @desps-iscteiulpt is there any success with NNv2 on the real market ? Why you choose this strat to run ?
