### ISSUE TITLE
gekko.js not found on path specified @Settings.py

### ISSUE THREAD

**Issue by CryptoCoeus** [Gab0/japonicus#156]
Hey Guys, 

Here is my folder structure : 
- / GA
   - /all cloned gekko files (so gekko.js is here)
   - /japonicus 
   - /venv (Python 3.6 & pip) 

I run this command under japonicus folder : 
`python japonicus.py -g -k --strat RSI_BULL_BEAR_ADX`

And i am having this error:
`Aborted: gekko.js not found on path specified @Settings.py`

Can you please help me to update the related param at Settings.py ?

**Comment by Gab0** [comment]
Hey, this path is under settings/global.yaml

**Comment by CryptoCoeus** [comment]
Thanks @Gab0  ! Btw, thanks for the whole project 👍
