### ISSUE TITLE
Updating Strategies & Parameter Ranges 

### ISSUE THREAD

**Issue by CryptoCoeus** [Gab0/japonicus#158]
Hey guys, 
japonicus.log file starting with declaring parameters ranges. However, I could not find the where we are setting ranges for parameters. Where is that "%30" range is setted ? :) 

And also, I have a question on updating strategies. 

So, strategy_parameters/RSI_BULL_BEAR_ADX.toml file have these 3 parameters 
```
short                         (7.0, 13.0)
low                           (56.0, 104.0)
mod                           (14.0, 26.0)
```
those are not included latest RSI_BULL_BEAR_ADX strategy of xFFFFF. Here is the [.toml file](https://github.com/xFFFFF/Gekko-Strategies/blob/master/RSI%20Bull%20and%20Bear%20-%20ADX%20modifier/RSI_BULL_BEAR_ADX.toml). 

And that .toml file has following parameters, instead of ours.. 
```
# MODIFY RSI (depending on ADX)
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 15
BEAR_MOD_low = -5
```

Thus, I have updated configStrategies.py file, 

 ```
"RSI_BULL_BEAR_ADX" : {
        # SMA Trends
        "SMA_long": 1000,
        "SMA_short": 50,
        # BULL
        "BULL_RSI": 10,
        "BULL_RSI_high":  80,
        "BULL_RSI_low" : 60,
        # BEAR
        "BEAR_RSI": 15,
        "BEAR_RSI_high": 50,
        "BEAR_RSI_low" : 20,
        # ADX
        "ADX": 3,
        "ADX_high": 70,
        "ADX_low": 50,
         # Modify RSI 
        "BULL_MOD_high": 5,
        "BULL_MOD_low": -5,
        "BEAR_MOD_high": 15,
        "BEAR_MOD_low": -5
    },
```
And also, strategy_parameters/RSI_BULL_BEAR_ADX.toml file with these parameters.  

However these 4 parameters are not on the japonicus.log file.. Thus, their range is not settled.. Where else i should update ? :) 

Cheers,

**Comment by Gab0** [comment]
Hey, the % spread can be edited at `settings/generations.toml`.
About the parameter names, we are talking about different versions of the strat here... You can replace the `.toml` at `strategy_parameters` for the `.toml` file that corresponds to your strategy file ofc.
cheers!

**Comment by CryptoCoeus** [comment]
Thx @Gab0 ,
