### ISSUE TITLE
Tulip indocators

### ISSUE THREAD

**Issue by AJ-gohan** [Gab0/japonicus#165]
when I run my custom strategy I get the following error, how can I enable Tulip indicators? 
 Error: non-error thrown: 
   ERROR: Tulip indicators is not enabled

**Comment by Gab0** [comment]
Hey, this is an issue with gekko, you should check their docs...
Anyway, using tulip with GA will result in too long processing time, so not recommended.
Try to use gekko native indicators only.
cheers!
