### ISSUE TITLE
Error EADDRINUSE

### ISSUE THREAD

**Issue by Kralg** [Gab0/japonicus#51]
Hello, 

I am trying to run Japonicus but I am getting error and there is nothing going on on the dashboard. Can somebody elaborate on this and give some ideas on what can be wrong?

I am starting it with
sudo python3 japonicus.py -b -c -k --repeat 10 -i -w
And I am running it on Virtualbox Ubuntu.

`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
WEBSERVER MODE
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
`

![screenshot from 2018-01-17 14-10-48](https://user-images.githubusercontent.com/26962388/35042349-014ff566-fb91-11e7-8ef2-339a0a4974b0.png)

**Comment by Gab0** [comment]
@Kralg, no benefit from running japonicus as root, unless you do that to fit your setup (virtual machine) or whaterver.
 It appears a gekko instance is already running, try removing `-k`, which starts a new Gekko instance, from your command ;d.

**Comment by Kralg** [comment]
Thanks! :) Now there is no error, but I still can not see any graph on the localhost:5000 even though I check "Every 15seconds". I can see that the datetime is changing below the "Every hour" but there is no graph on the screen or anything else.  Can you suggest what could be the reason for that?

**Comment by Gab0** [comment]
I think `-b` mode, the bayesian evaluator, is not compatible with graphics..,
Run a `-g` session instead, and wait some epochs to check the graphic output.

**Comment by Kralg** [comment]
Thanks a lot! Now I can see something. 
I am quite new in Japonicus. Can you write a bit on how are the results presented, so there will be multiple runs and the best coefficients of a the strategy will be presented at the end?

**Comment by Gab0** [comment]
As it is, some results are presented at the end of all EPOCHS if deemed valid on further simulations.. not even worth writing about it XD. 
Theres room for elaborate things on this side, also would be quick to implement... so I may put the code and instructions on following days ;)
