### ISSUE TITLE
Add Setting.py key to turn on gekko debug

### ISSUE THREAD

**Issue by trainerbill** [Gab0/japonicus#55]
https://github.com/Gab0/japonicus/blob/master/promoterz/evaluation/gekko.py#L178

**Comment by Gab0** [comment]
@trainerbill maan please elaborate..

**Comment by trainerbill** [comment]
Can you add a key in the settings.py file that turns the debug flag on and off on that line in the link above?  Currently you are surpressing debug output on gekko when spawning so if I do a log.debug in my strat it never outputs

**Comment by Gab0** [comment]
Oh, nice idea!

**Comment by Gab0** [comment]
It seems to not work.. gekko do not show debug from backtesting on API calls.

**Comment by trainerbill** [comment]
It works.  I also have this flipped to True

https://github.com/Gab0/japonicus/blob/master/japonicus.py#L45

It helps me see what gekko is receiving from japonicus.
