### ISSUE TITLE
Floats and Float Precision

### ISSUE THREAD

**Issue by trainerbill** [Gab0/japonicus#56]
Seems like all the output is in floats.  This is just going to increase the combinations.  Example output
```
 -- Settings for Gekko --ui webpage -- 
persistence = 2.5300000000000002
[PPO]
short = 10.67
long = 23.270000000000003
signal = 4.8
up = 0.1009
down = -0.79021

[TSI]
up = 10.0
down = -34.9
long = 36.56
short = 6.449999999999999
```
Here is my configStrat
```
"PPOTSI":{
        "PPO.short": (3,16),
        "PPO.long": (12,35),
        "PPO.signal":(3,21),
        "PPO.up": (0.001, 1),
        "PPO.down": (-1, -0.001),
        "TSI.up": (10,40),
        "TSI.down": (-40,-10),
        "TSI.short": (3,18),
        "TSI.long": (10,42),
        "persistence": (1,10)
    },
```
The only floats should be PPO.up and PPO.down but all the params are floats.  I would also like to be able to set the precision on the ones that are floats.  0.001 should only test floats to that precision.

**Comment by Gab0** [comment]
The GA workings doesn't discriminate floats from ints, all numbers are formed like `"PPO.short": (3,16) --->>> number = ga_magic_float * (16-3) + 3`.. the precision can be worked out later yeah.

**Comment by trainerbill** [comment]
I don't know anything about the GA algorithm but doesn't this introduce a ton of new combinations?Like the int PPO.short could be evaluated as 23.111 or 23.11 or 23.1 instead of 23, 24, 25.

**Comment by Gab0** [comment]
Gekko just rounds the float to int. All those new floats are not detrimental to the algo, as its not testing all possible combinations..
The steps can be made shorter by changing genconf.GeneSize to greater number on settings. (for `-gc` method)
