### ISSUE TITLE
Add DateRange tested and historySize to the settings output / Clarify settings

### ISSUE THREAD

**Issue by trainerbill** [Gab0/japonicus#57]
I am comparing the output from japonicus and a manual run in gekko but I don't know what daterange and historySize japonicus is using.  Would be nice to display them in the profit output or at least once at the beginning of the output.  there is currently output first

```
using candlestick dataset 2018-01-01 00:38:00 to 2018-01-21 19:38:00
```

but it is unclear what is actually being tested in gekko because I am unsure what this setting does:

https://github.com/Gab0/japonicus/blob/master/Settings.py#L43

Or can we add a daterange setting here: https://github.com/Gab0/japonicus/blob/master/Settings.py#L66

Anything to make it easy to take the output from japonicus and run the exact backtest in gekko.

**Comment by Gab0** [comment]
Each LOCALE on the GA loads a random section of your database of length = deltaDays (days), and keeps it until it ends. It can be changed to show the daterange loaded on each locale.. keep an eye for the update.
