### ISSUE TITLE
Run Error with Bayesian

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#59]
Hello, I've been trying to run GA with no success (I'll make separate post), so I thought I'd try Bayesian, and I'm getting the following error when trying to run `python3 japonicus.py -b --strat PPO`

```
The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Traceback (most recent call last):
  File "japonicus.py", line 102, in <module>
    import evolution_bayes
  File "/home/user/gekko/japonicus/evolution_bayes.py", line 19, in <module>
    import chart
  File "/home/user/gekko/japonicus/chart.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```

Any thoughts would be appreciated, Thanks!

**Comment by Gab0** [comment]
Hey, bayesian is really dysfunctional atm, next commit in following mins got it fixed on my machine. Update, try again, and report resultz ;D

**Comment by Gab0** [comment]
Fixed.

**Comment by BradT7** [comment]
Same issue again... btw I am able to run a successful backtest within Gekko with the same gdax datasets.
I'm currently downloading a poloniex dataset, as that seems to be the default, and will test with that shortly as opposed to gdax dataset.
I must admit I am new to linux, (on latest linux Mint from a few days ago updates all done) and have a basic understanding of coding. I did install python 3.6.4 manually from the python website, seems like others are having issues with tkinter missing around the web as well.  
Sorry for the noob question, but is there a better way to install python instead of manually downloading it from their site and making it (found a thread on how to install it manually). If so do you have a link to a preferred method I could follow and how to uninstall existing 3.6.4 (I understand not to uninstall version 2 when reading around the web) 
It looks like python is installed in my home folder as well, is that an issue? 
Also, japonicus is also in my home folder, does it need to be located inside the gekko folder or is it okay in home folder?
Thanks for your help!

```
$ python3 japonicus.py -b --strat PPO
	GEKKO
     ██╗ █████╗ ██████╗  ██████╗ ███╗   ██╗██╗ ██████╗██╗   ██╗███████╗
     ██║██╔══██╗██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝██║   ██║██╔════╝
     ██║███████║██████╔╝██║   ██║██╔██╗ ██║██║██║     ██║   ██║███████╗
██   ██║██╔══██║██╔═══╝ ██║   ██║██║╚██╗██║██║██║     ██║   ██║╚════██║
╚█████╔╝██║  ██║██║     ╚██████╔╝██║ ╚████║██║╚██████╗╚██████╔╝███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═════╝ ╚══════╝
								v0.29

The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Traceback (most recent call last):
  File "japonicus.py", line 102, in <module>
    import evolution_bayes
  File "/home/user/japonicus/evolution_bayes.py", line 19, in <module>
    import chart
  File "/home/user/japonicus/chart.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```

**Comment by itenev** [comment]
The following issue appears to be related. It refers to tk packages not being installed with Python:

https://github.com/matplotlib/matplotlib/issues/9017/

**Comment by BradT7** [comment]
Looks like I installed manually as well like this thread, and did not include tk library from what I'm reading, now the journey begins on how to uninstall 3.6.4 and re-install properly with tk included. Anytime I try installing or downloading tk manually from terminal I get errors.

I ran into another issue on another machine I was trying to install everything fresh. I was able to install python in usr/lib using some other install method, but whenever I install or run any pip commands, everything is installed to the 3.5 python folder, for example after running the pip installer, deap is located in the 3.5 folder not 3.6. So I ran into another road block. I can run a `python3.6` command, but a `pip3.6` is not supported and errors. so `pip3` is running from version 3.5. So frustrating. 

So maybe the take away is how do I properly install python, or the necessary way for japonicus, and how to I default pip and python to run from version 3.6 when python is installed in usr/lib. 

I was able to try and just download but again it installed to my 3.5 folder, and still getting the tk error
```
$ sudo apt-get install python3-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  tix python3-tk-dbg
The following NEW packages will be installed:
  python3-tk
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 25.1 kB of archives.
After this operation, 89.1 kB of additional disk space will be used.
Get:1 http://mirror.csclub.uwaterloo.ca/ubuntu xenial/main amd64 python3-tk amd64 3.5.1-1 [25.1 kB]
Fetched 25.1 kB in 0s (330 kB/s)
Selecting previously unselected package python3-tk.
(Reading database ... 202562 files and directories currently installed.)
Preparing to unpack .../python3-tk_3.5.1-1_amd64.deb ...
Unpacking python3-tk (3.5.1-1) ...
Setting up python3-tk (3.5.1-1) ...
```
Not sure if the way I installed python is also affecting issue 60, but I actually get further results with the GA method.

**Comment by BradT7** [comment]
I found the solution to my last post! :D Using the same method that fixed  my GA error (Issue 60).
After installing python properly using method you mentioned [here](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get)
Then running the following commands:
`sudo apt-get install python3-tk`
`sudo python3.6 -m pip install python-tk`

Hope this helps any others that may run into this issue!
