### ISSUE TITLE
Missing coma

### ISSUE THREAD

**Issue by grogcw** [Gab0/japonicus#61]
Hi !

Just to let you know that it now runs smoothly, but for beginners, there's a missing coma in Settings.py here :
            'RemoteAWS': '../AmazonSetup/hosts'
it should be :
            'RemoteAWS': '../AmazonSetup/hosts',

Thanks for you work again !

(this fix should take about 5 sec to fix in github....YMMV 😄 )

**Comment by Gab0** [comment]
XDD thanks for the report ;) fixed
