### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by coltac** [Gab0/japonicus#62]
Okay i have japonicus up and running

I run  $ python3 japonicus.py -g -w -i --strat PPOTSI
It comes up with nice profit numbers etc. 

How do i know which dataset is being used.  (i set one in settings.py (ETH / ICX))
How do i know the candle size that it came up with the settings for?

Thanks, and this software is pretty darn sweet!

**Comment by coltac** [comment]
Ahh, i found a candle size settings in settings.py, missed it 20 times

**Comment by Gab0** [comment]
Nice, remember each locale evaluates only a slice of the dataset. 
Cheers!
