### ISSUE TITLE
Backtest

### ISSUE THREAD

**Issue by Deepdelver** [Gab0/japonicus#63]
I see that japonicus generates strategie's. But how can i use them to backtest or trade bot?

And Is it possible to contentiously use the best test result of a strategie?

**Comment by Gab0** [comment]
Generated strategies are stored under `strategies/japonicus`on your Gekko setup.
You can select by setting its name on gekko's `config.js`, like  `mehod: japonicus/jc738RSISMMA`. Remember to put corresponding config on `config.js`
