### ISSUE TITLE
Questions - Testing Multiple Trading Strategies

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#65]
Hello again, 

I was looking over your configStrategies file, and see the blending of two pairs, which lead to some questions.

- Do the results of these tests imply both criteria have to be met for a trade to execute?
- Is it possible to add three pairs or even four pairings to GA test at the same time?
- Can other pairings be used outside of the default gekko strategies?
- Is it better to GA test strategies individually and then merge those best results into a pairing GA test, or just run them with defaults paired from the beginning?
- I've briefly looked at that supertrend strat, looks really neat, and installed talib to gekko, but am not seeing anything new in the gekko dropdowns, am I missing something?
- Does talib include Bollinger Bands? I would be interested in running a GA pairing including BB, but might need some more resources to learn how to achieve that.

Any links or insight into the above questions to point me in the right direction would be very appreciated.
Thanks in advance! I'm still very new to all this.

**Comment by Gab0** [comment]
The GA runs any strat that works on gekko alone. We're free to add how many pairings we wish ;d, in any combinations. Just make sure those settings on configStrategies are valid.
The indicators alone works very differently from when together on same strategy, thats actually a very chaotic science, so we are here to test stuff. A strat with one indicator on its threshold mostly does not work.
TA-Lib indicators take much CPU tiime, so BB that lib (existis indeed) is not suitable for GA usage. I have ported BB to native gekko, heres the file:

BB.js
```
// required indicators: SMA;
// port by Gab0 - 2017
// not exact results when compared to TA-Lib but GOOD ENOUGH;
// Bollinger Bands implementation;

var SMA = require('./SMA.js');
var Indicator = function(BBSettings) {
    this.input='price';
    this.settings = BBSettings;

    this.center = new SMA(this.settings.TimePeriod);

    this.lower=0;
    this.middle=0;
    this.upper=0;
}

Indicator.prototype.calcstd = function(prices, Average)
{
    var squareDiffs = prices.map(function(value){
        var diff = value - Average;
        var sqr = diff * diff;
        return sqr;
    });

    var sum = squareDiffs.reduce(function(sum, value){
        return sum + value;
    }, 0);

    var avgSquareDiff = sum / squareDiffs.length;

    return Math.sqrt(avgSquareDiff);
}

Indicator.prototype.update = function(price) {
    this.center.update(price);

    this.middle = this.center.result;
    var std = this.calcstd(this.center.prices, this.middle);

    this.lower = this.middle - this.settings.NbDevDn * std;
    this.upper = this.middle + this.settings.NbDevUp * std;
}

module.exports = Indicator;


```

**Comment by BradT7** [comment]
Thanks, I'll see if I can figure that out after my existing GA finishes!

**Comment by BradT7** [comment]
Hi Gab,
I was able to get the Supertrend working, just running it now! 
But not having much success with BB.js
I tried mimicking the Supertrend setup, but wasn't successful.
I placed BB.js in gekko/strategies/indicators 
I tried adding it to config.js, configIndicators.py and configStrategies.py
Are there any other files missing needed? Does anything have to be placed in gekko/strategies folder?
Are there any other variables that need to be defined other than lower, middle, upper?
Thanks!

**Comment by BradT7** [comment]
Hi @Gab0,

I recently found a [BB.js strategy](https://github.com/askmike/gekko/pull/1623/files) and was able to get it to run successfully within gekko UI, but I'm having some difficulty running it with japonicus.

I've added the following to configIndicators.py and configStrategies.py
cI
```
    "BB":{
        "active": True, # [bbands]
        "TimePeriod": (15,25), # 20
        "NbDevUp": (1,3), # 2.25
        "NbDevDn": (1,3) # 2
    },
```
cS
```
    "BB": {
        "BB.TimePeriod": (15,25), # 20
        "BB.NbDevUp": (1,3), # 2.25
        "BB.NbDevDn": (1,3), # 2
        "persistence": (1,10)
    },
```
config.js
```
config.BB = { 
    TimePeriod: 20,
    NbDevUp: 2.25,
    NbDevDn: 2
}
```
But I'm getting errors when running `python3.6 japonicus.py -g --strat BB`
[https://pastebin.com/jE92ff5p](https://pastebin.com/jE92ff5p)

Any ideas on what I'm doing wrong and how to get this to run correctly?

Once I know it's working, eventually I will attempt tweaking your PPOTSI.js as a template to attempt other pairings on my own.

Thanks!

**Comment by BradT7** [comment]
I figured it out! I just updated cS to bbands and it's currently running! :D 
cS
```
    "BB": {
        "bbands.TimePeriod": (15,25), # 20
        "bbands.NbDevUp": (1,3), # 2.25
        "bbands.NbDevDn": (1,3), # 2
        "persistence": (1,10)
    },
```
Any tips/insight on persistence? Not sure if it was even necessary, Thanks!

**Comment by Gab0** [comment]
Nice @BradT7  ;D.. persistence was something I was developing, dunno if was applied or not.. something about the trend of each indicator.
Remember `-i` is beta as hell and pull requests are welcome.

About supertrend, some strats are not suitable for japonicus before some small modifications. Some of em have config hardcoded on them. Should always pull settings from `this.settings`.
Cheers!

**Comment by BradT7** [comment]
Hi @Gab0 I found a JS that blends StochRSI MACD and BB, and I'm trying to run it through Japonicus, but can't figure out how to get the config to take, keep getting config errors on a -g or -b run.
This is the toml file, which does work when run through the gekko ui, but translating it to your cI and cS is where I believe I'm running into issues.

toml is
```
short = 10
long = 21
signal = 9
interval = 3

[thresholds]
down = -0.025
up = 0.025
persistence = 1
low = 20
high = 80

[bbands]
TimePeriod = 1
NbDevDn = 1.96
NbDevUp = 1.96
```
This is what I have in the cI and cS (minus active line in cS), but is not running -g or -b, gives config error right away. I tried defining the items like MACD.short thinking that would help, but same issue.
```
    "StochRSI_MACD":{
        "active": True,     
        "MACD.short": (5,15),     # 10
        "MACD.long": (20,25),      # 21
        "MACD.signal": (7,11),     # 9
        "StochRSI.interval": (2,4),   # 3

        # [thresholds]
        "MACD.down": (-0.02,-0.03),  # -0.025
        "MACD.up": (0.02,0.03),     #  0.025
        "StochRSI.persistence": (1,5),# 1
        "StochRSI.low": (10,30),       # 20
        "StochRSI.high": (70,90),      # 80

        # [bbands]
        "bbands.TimePeriod": (1,22),  # 20 (default was 1)
        "bbands.NbDevDn": (1.7,2.3),  # 1.96 or 2.25
        "bbands.NbDevUp": (1.7,2.3)  # 1.96 or 2
    },
```
I noticed in the gekko UI if I take out the [thresholds] or [bbands] lines it also fails to run in the ui, but I'm not aware of a way to include those lines in you cI or cS files, as I see they are not used elsewhere.

Any insight would be much appreciated, this seems to be the setup that works best for casual trading from what I've been reading, but would love to run it through a GA like yours!

**Comment by Gab0** [comment]
The toml file indicates the structure of the config dictionary. so its like this:

"StochRSI_MACD": {
"short": (5,15),
"long":,
"signal":,
"interval":,
"thresholds": {
  "down" "up" "low" etc
  },
"bbands": {
    "TimePeriod", .......
}
}
