### ISSUE TITLE
Running as background process and reading output

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#68]
Is there any way to run it as a background process? And how can I read the output files? The evolution_gen_*.csv files seem to contain numbers that don't have any labels and don't look like any of the parameters. 

Would be good to be able to run it as a background process, and come back later to find the best settings that it found.

**Comment by Gab0** [comment]
You could run gekko and japonicus and minimize those terminals xD
tmux is another option, check some tutorians on the webz, there are plenty.

**Comment by shuruheel** [comment]
Went for tmux. Works like a charm. Thanks!
