### ISSUE TITLE
GA Not Trading or Lack of Trading

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#70]
Hello,
I'm having some issues after running multiple GA tests on a BTC dataset starting Jan 1, 2017 to Now.
What seems to be happening, no matter the strategy (just ran single strategies so far), is it will only perform maybe 1-3 trades, if I'm lucky it will perform a cluster or trades until around April, and then just stop trading after that. This is seen after plugging in the end results after 400 epochs into the gekko ui site. So the result is really just a buy and hold result, which obviously isn't the idea here.

The time frame is the default 15 minutes for now, but that shouldn't matter when it comes to something like [PPO compared to MACD](http://stockcharts.com/articles/mailbag/2014/03/ppo-vs-macd-when-to-use-the-other.html) where the huge run up after April shouldn't have had much effect of the PPO trading indicator. But my PPO GA only ran one trade after running the results of 400 epochs. This is the same for CCI and UO too.  I was able to get proper trading results using Supertrend, but it just didn't exceed the buy and hold results.

Am I missing something here? Is there a way to force it to trade more? Do I need to reduce the trading snapshot for an epoch to less than 60 days (I think that's the default I've seen). Any other tips?  Thanks!

**Comment by Gab0** [comment]
Lowering `candleSize` tends to result in more trades, due to more ticks on the strategy.
You could also lower top thresholds and raise low thresholds ranges of your strategy settings, resulting on more trades. 
As far as I know japonicus does not have a bug in that department, but who knows? I'm running some tests.
