### ISSUE TITLE
Reading evolution_gen.log and other output after -i

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#72]
I ran japonicus with the -i flag, letting it try different indicator combinations to find the best. But the log and output makes no sense to me? See the following example. Every item in evolution_gen.log has parameters for ALL the indicators, rather than the combination which was tried. 

~~~~~~~~~~~~~~~~~~ 202.275 final profit ~~~~persistence = 2.92
[CCI]
active = 0.61
consistant = 17.78
history = 112.5
[thresholds]
down = -125.0
persistence = 9.04
up = 102.0


[DEMA]
active = 0.48
long = 25.34
short = 14.84
[thresholds]
down = -0.020000000000000004
up = 0.058


[LRC]
active = 0.97
depth = 14.1
[thresholds]
down = -19.6
up = 29.8


[PPO]
active = 0.07
long = 30.68
short = 6.24
signal = 1.34
[thresholds]
down = -0.4
up = 0.46


[RSI]
active = 0.7000000000000001
interval = 13.3
[thresholds]
down = 42.9
up = 102.0


[SMMA]
active = 0.03
weight = 13.66
[thresholds]
down = -0.04700000000000001
up = 0.013000000000000001


[TSI]
active = 0.52
long = 17.4
short = 11.28
[thresholds]
down = -20.799999999999997
up = 25.6

Facing the same issue with the Locale .csv files. What do these numbers mean? The first one is the counter, but the rest just seem to be random numbers. 

183,34.9009343945,67.1229119943,-196.80028122,55.2570792559,None

**Comment by Gab0** [comment]
`-i` method is highly experimental and poorly documented yet XD
Each individual got all of the parameters of every inticator. 
But the used indicators on eval are only the pair with highest `active`parameter, in sample case LRC+RSI.
That result seems to be good. You could run LRCRSI strat on `gekko/strategies/japonicus/`with those settings. 
If you need further help to do that, comment here ;d the README fails on `-i` mode for sure.

**Comment by shuruheel** [comment]
No complains. What you've done is phenomenal as it is hehe. 

That makes this output file a lot more interesting! Is it possible to just copy this strategy from gekko/strategies/japonicus/ to gekko/strategies/ and run a backtest on it via the UI? I tried to do that once but the parameters part in the UI was empty, and the strategy wouldn't work in the backtest. Will try again. 

Let me know if you think I might be missing a step e.g. maybe something needs to be added to the gekko config?

**Comment by Gab0** [comment]
You could copy just LRC section and RSI section of the result to gekko's UI. 
The stratname would be like `japonicus/jcNNNLRCPPO`. 
To add a strat to UI you have to recompile it, thats covered on gekko docs.
 Backtesting via command line would be easier, but settings should be ported to `config.js`json format.
