### ISSUE TITLE
Question about how to handle correctly the result

### ISSUE THREAD

**Issue by Antexa** [Gab0/japonicus#73]
Hi @Gab0, 

I was wondering how to properly handle the result of a backtest, I'm aware about the specificity of result is linked to the dataset we specified. 

But what is the best way to set up correctly our strat ? 

3 settings of our toml with bear market, bull and sideway ? 
1 setting for rule them all ? 

I would like to know your opinion about that.

**Comment by Gab0** [comment]
Hey @Antexa, to take best advantage of genetic algorithms, the bigger number of settings, the better.
