### ISSUE TITLE
Backtesting platform

### ISSUE THREAD

**Issue by donkykong017** [Gab0/japonicus#75]
Which backtesting platform do you use. I tried on my raspi, which obviously is not made for that task and takes ages.
Then I went on to aws, which in the free tier is not better than the raspi even with spread load on several instances. Thought about running japonicus on a powerful instance and spreading gekko on several free ones. But as it looks that's going to become expensive fast anyways. Problem is the data transfer as far as I found out.
Lastly I got everything to run on my laptop, which is in the end the fastest one but also takes days.
I'm now thinking about combining the possibilities.
Please let me know how you do it. Thanks

**Comment by nimasTT** [comment]
i use at the moment some azure trial servers. ~750 h free. But it's also not much faster than my laptop.
Think in the cloud would be Dockerized variant cheaper.

**Comment by donkykong017** [comment]
Thx for the reply. Yeah docker is the next thing to look at an "learn" as everything when i started with the project as a complete noob.
Just thought to test things and debug to start of without time limits, running everything on a laptop or such would be the best way. Good thing im just looking to buy a new one.

**Comment by Gab0** [comment]
You can mess with candleSize and `genconf.ParallelCandlestickDatabase`, among other settings, on `Settings.py` to get faster epoches. It should run fine on a core i5, in a matter of hours. Also, spot requests on AWS are much cheaper.

**Comment by donkykong017** [comment]
thx for your answer. i got a new laptop and messed a little bit with the settings. i can get much faster results now. for me the laptop is still the best and most convenient back-testing platform.
closing this now

**Comment by CryptoCoeus** [comment]
everytime i run japonicus via pycharm ide, my mac is creating a noise like a helicopter :) Has anybody tried to run japonicus on heroku ?

**Comment by Gab0** [comment]
@CryptoCoeus it is easy to setup it on AWS. Heroku would be complicated I guess.
