### ISSUE TITLE
ParallelBacktests config var not being used?

### ISSUE THREAD

**Issue by danjiro** [Gab0/japonicus#78]
I'm trying to increase my # of ParallelBacktests but it seems to be hardcoded to 5 and the variable in Settings.py doesn't seem to do anythings. Is this true of candleSize as well? This is for genetic algorithm and not bayesian.

**Comment by Gab0** [comment]
ParallelBacktests is really broken, was hardcoded to 4. Next commit will fix it ^^
candleSize seems to be working well.

**Comment by danjiro** [comment]
for GA it still seems to be set to 5? not 4...Can you specify where in the code this is set?

**Comment by Gab0** [comment]
At ./promoterz/world.py:25:  it calls the class of ./promoterz/evaluationPool.py using the settings, and the class init function sets self.poolsizes accordingly.
lulz oh wait it sets self.poolsizes to five for each Urls XD. Was really hardcoded to 5, fixing it ^^.
