### ISSUE TITLE
KeyError: 'Strategy'

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#81]
Getting the following error when trying to run Bayesian optimization after updating to the latest branch (genetic still works): 

  File "japonicus.py", line 108, in <module>
    import evolution_bayes
  File "/root/gekko/japonicus/evolution_bayes.py", line 27, in <module>
    Strategy = settings["Strategy"]
KeyError: 'Strategy'

**Comment by Gab0** [comment]
Nice... problem solved on latest commit.
