### ISSUE TITLE
Optimizing for multiple vCPUs

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#83]
Hey,

I'm running japonicus on a server with 8 dedicated vCPUs. Any tips on optimizing the config to maximize performance? 

Trying out ParallelBacktests=20. Would you recommend a higher number? Are there any other settings I should tweak?

**Comment by Gab0** [comment]
I would test ParallelBacktests=8, then to like 16 and see whats run faster. I bet its 8, one backtest for vCPU as node.js likes.  I think thats all about it ^^
