### ISSUE TITLE
AssertionError - After Recent Update/Download

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#84]
Hello, I recently downloaded and updated gekko and japonicus to the latest versions, and now I'm unable to complete full epochs. I get the following error at a random epoch level, usually 100+ as high as 300+ sometimes. (I've updated .py files manually from backup japonicus files to add in custom strategies again.)

```
Traceback (most recent call last):
  File "japonicus.py", line 105, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/brad/japonicus/evolution_generations.py", line 108, in gekko_generations
    World.runEPOCH()
  File "/home/brad/japonicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/home/brad/japonicus/promoterz/locale.py", line 51, in run
    self.loop(self.World, self)
  File "/home/brad/japonicus/promoterz/sequence/standard_loop.py", line 11, in standard_loop
    assert(len(locale.population))
AssertionError
```

Does this trigger anything for you as to what could be causing this?
It's the same strategy just different pairings, I noticed the new version is much faster BTW, excellent work!

**Comment by Gab0** [comment]
Hey, that zero population error occours when all of them didn't get minimum score. So the strat probably failed. Which whas that strat. Anyway, its faster because some obscure settings have changed... not software engineering magic ^^. Cheers!

**Comment by BradT7** [comment]
Weird, it was RSI_BULL_BEAR, BTC/XRP. ADX also had similar error. It did
have successful epoch results before the error, it should at least display
the most successful results before erroring/stopping. I'll keep trying.
Also its speed is much faster with talib/tulip than before I updated :)

On Feb 20, 2018 4:45 PM, "Gabriel Araujo" <notifications@github.com> wrote:

Closed #84 <https://github.com/Gab0/japonicus/issues/84>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gab0/japonicus/issues/84#event-1483438903>, or mute the
thread

**Comment by Gab0** [comment]
@BradT7 Strange to fail on RBB, maybe if you tried again... 
I'm figuring out the result report system, it a bit shitty at the moment but hey... that 'best result' you want shall be really useless in that case... guaranteed hahah. 
The low score threshold should on the settings on a near update, keep calm ;D

**Comment by BradT7** [comment]
Another update for you on this. I got this error again after updating everything again, and it seems like once I disabled debugging on the RSI_BULL_BEAR_/(ADX) everything is running smoothly again. So perhaps it's not able to keep up with the gekko debug log, or going to fast something is falling behind.

BTW your mods of these scripts are insanely fast!! Bravo!! I got some results I'd like to share with you privately as the developer :)

**Comment by Gab0** [comment]
Hey @BradT7, report the effects of those modes on the virtual machine. btw feel free to email me with hot evolutionary data x]

**Comment by BradT7** [comment]
After setting the Parallel back tests back to the default value of 6, it seems to have resolved my AssertionError's, even though the number is much lower than the available CPUs (32) the individual gekko results are actually much faster, so it ends up taking about the same amount of total time, but without random AssertionError's to deal with. I think low memory was also an issue at the time I had the parallels set to double or more. I’m using Hyper-V for the VM of Linux Mint, and when running 6 parallels at a time, Hyper-V is saying my memory demand is around 22 GB (I've allocated 32GB). Hope that is useful in case anyone else ever runs into this error. Looks like I’m all good now! :)

**Comment by Gab0** [comment]
@BradT7 nice insights on how parallel stuff works. The upcoming update will hopefully fix those assertion error.

**Comment by BradT7** [comment]
Hate to say this, but I'm still getting these errors, it's difficult to finish a full 800 epochs. It's very random too, sometimes only 50 epochs in, other times 750. Eventually it'll finish, but very random, it's hard cus I can't run things overnight. I'm going to try reducing the parallels from 6 to 4 tonight, as well as the recent git pull from the last few couple days.

```
Locale6
Traceback (most recent call last):
  File "japonicus.py", line 110, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/brad/gekko/japonicus/evolution_generations.py", line 166, in gekko_generations
    World.runEPOCH()
  File "/home/brad/gekko/japonicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/home/brad/gekko/japonicus/promoterz/locale.py", line 49, in run
    self.loop(self.World, self)
  File "/home/brad/gekko/japonicus/promoterz/sequence/standard_loop.py", line 11, in standard_loop
    assert(len(locale.population))
AssertionError
```

**Comment by BradT7** [comment]
New update! Either the latest git pull or changing parallels from 6 to 4 has resolved this error for over 8 full 800 epochs! I'll probably just leave it at 4, as it doesn't really effect the total time taken. The 4 individual parallels just run and finish faster, compared to running like 12 for example.

**Comment by Gab0** [comment]
Hey, over the last updates things have changed on the discard of individuals that leads to population of zero, then to this assertion error. It has nothing to do with parallels config, and it should not happen again. If it happens please report, would be a bug... cheers!
