### ISSUE TITLE
Question - Variables, More than 400 Epochs

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#85]
Hello,
I have yet to run any tests with more than 400 epochs, but was wondering your thoughts on increasing that number, do you have any experience doing so? Does it possibly improve results? I remember reading somewhere on a GekkoGA post, someone running it and finding the best result around 700 epochs and then it stopping after 100+ more epochs providing no better results. I never did have any success running GekkoGA before finding out about Japonicus, but that intrigued me as to whether more epochs could provide more beneficial results. Your thoughts?
Also, would be interested in your thoughts to how Japonicus differs from GekkoGA.
FYI for some other variables I've tweaked, I tried POP_SIZE at 15 rather than 30, and deltaDays at 30 rather than 60, and the results were extremely poor compared to the default values for those variables.
Thanks!

**Comment by donkykong017** [comment]
I have yet to run more than 400 epochs, but the best results where in the beginning to middle epochs. I have not messed with any other variables yet.
As I saw some of the variables have changed in the last update. will try that soon with the same data to see the difference.

**Comment by Gab0** [comment]
Yeah, it seems that after epoch 150 the results seems to deteriorate. It depends on the strategy.
