### ISSUE TITLE
Dataset Used 

### ISSUE THREAD

**Issue by donkykong017** [Gab0/japonicus#86]
During running japonicus when i run a historic market data import at the same time will the backtests also use the newly imported data? as i think about it, this could be more a gekko than a japonicus question. anyways 
When importing data in gekko it is already available to backtest during the import.
Is japonicus using different delta.days parts of the data? and will it use the newly imported data let's say when i run a market watcher?

**Comment by Gab0** [comment]
japonicus selects the largest, on timespan, dataset you have. Unless you specify one at `Settings.py`.

**Comment by donkykong017** [comment]
Thx for your answer @Gab0. I thought that it will do that. But what happens when i specify a dataset to use. Will it use newly fetched candles during a running backtest? And how does it spread the delta days over a large dataset. Will it try to use as much different spans (delta days) as possible?

**Comment by donkykong017** [comment]
another question that came to my mind was:
is it possible to specify a time range japonicus will backtest on? like in gekko ui e.g.
looked through the files but could not find that

**Comment by Gab0** [comment]
Hey @donkykong017, each locale that holds its own population selects a random piece of the dataset, of lenght deltaDays in days, and backtests on it at every epoch.
 Selecting a particular range of the dataset to used could be coded... but why, exactly? I don't see a practical purpose... cheers ^^

**Comment by donkykong017** [comment]
cheers @Gab0 . thx again for your reply!
ok i get it. thx for the info. it was what i was looking for. i agree with the random selection of pieces in deltaDays length. what i am trying to accomplish  is to cut the whole dataset used initially to like two month in the past from now. lets say i have a strat runner or market watcher and imported data from the beginning of 2016 to current date refreshed with the market watcher. and i have a live bot running with that same market watcher. what i want to do is use GA to fine tune the parameters for the live gekko with the last to month of data. so cut 2016-current time to 1.1.18-current time and backtest GA on that timeframe.
i think testing the strat with GA on the whole dataset would overengineer it. as the market is changing rapidly imho it seems more practical to tune it to the last weeks or month of data and update it periodically. i think there is no perfect strat for a given market. its better to tune an tweak it regularly.
what would you say?
cheers

**Comment by Gab0** [comment]
haa @donkykong017 yeah, agreed.. that will be online soon, check `Settings.py` ;}

**Comment by donkykong017** [comment]
Awesome thx so much @Gab0
