### ISSUE TITLE
Explaining proofSize and DRP (Date Range Persistence)

### ISSUE THREAD

**Issue by shuruheel** [Gab0/japonicus#88]
What is proofSize and what unit is it defined in? 

And how does Date Range Persistence work? It is defined as the "number of subsequent rounds until another time range in dataset is selected". Are rounds the same as epochs? 

If the complete dataset covers 180 days, deltaDays is 60, and we want to run 600 epochs, DRP should ideally be 200, right? Or am I misunderstanding something?

**Comment by Gab0** [comment]
hey @shuruheel.. DRP is deprecated, it was used before the implementation of parallel GA where the dataset changed every DRP epoches... that way it has nothing to do with dataset lenght or deltaDays ;)

**Comment by shuruheel** [comment]
What about proofSize?

**Comment by Gab0** [comment]
Oh yeah hah.. `proofSize` is the number of sequential evaluations of those that happen each 20 EPOCHs.
