### ISSUE TITLE
Question - Evolution and Evaluation Datasets

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#92]
I've been selecting custom evolution datasets, but noticed the evaluation dataset is set to none, and therefore selecting a different pairing then the evolution dataset when running GA tests.
Is this an issue in terms of running proper tests? I'm still getting good results regardless, but perhaps they could be better if they match?
If Evaluation is intended to match Evolution, is it possible to mimic the settings structure for dataset_source and use if for eval_dataset_source too?
Could you please explain how these two work together for me.
Thanks!

**Comment by Gab0** [comment]
Hi @BradT7, eval_dataset still has no repercussion inside japonicus. Its only for user guidance. 
I think it just should be of different asset than evolution dataset.
The function of that seconday dataset is to measure evolution automatically, by backtesting against blind data. In the future it may have proper usefulness ;D
