### ISSUE TITLE
Can't specify a date range

### ISSUE THREAD

**Issue by mkondel** [Gab0/japonicus#95]
I can't seem to get gekkoga to use the latest date range that i have candles for. I imported 5 days of most recent data from gdax, but I also have older data from Dec being loaded. When I run gekkoga, it always picks the longest dataset. Here is how I start it:

```bash
python japonicus.py -g --strat neuralnet
......
evolution candlestick dataset 2017-12-04 00:33:00 to 2017-12-22 00:33:00
BTC/USD @gdax
......
```

Here is what i have in gekko at the moment:
![image](https://user-images.githubusercontent.com/3288757/36950914-e20e339e-1fca-11e8-9fc3-8e4af3c31928.png)

And here is part of my Settings.py:
```javascript
'dataset' : {
            # -- Gekko Dataset Settings
             # dataset_source can be set to None so it searches from any source;
            'dataset_source': { # in case of specifying exchange-currency-asset, rename this removing the '!', and del the original key above.
                "exchange": "gdax",
                "currency": 'USD',
                "asset": 'BTC',
                'ranges': [{'to': 1520116380, 'from': 1519677180}],
            },
            'eval_dataset_source': None,

            # span in days from the end of dataset to the beggining. Or zero.
            # (to restrain length);
            'dataset_span': 0,
            'eval_dataset_span': 0
        },
```

**Comment by Gab0** [comment]
Hey @mkondel. Are you trying to hijack our `Settings.py`, adding that `ranges` key? XD
That won't work, and at the moment its not possible to select from those seemingly equal datasets, something we are working on for the next versions.
By the way, those dataset lengths are inadequate for GA usage, you should get longer datasets (like six months of data) to work on. 
Cheers!

**Comment by mkondel** [comment]
Thanks for the info! Are you active in any discords for the current development? I'm on the new gekko server, as well as gekkoga and the old gekko section on cryptobots. I can probably help with some of the new dev.

**Comment by Gab0** [comment]
Yeah I'm casual at gekkoga discord server. look for `caval0ne`. Can you dev? pm me there :)
