### ISSUE TITLE
[Community Request] Test Run

### ISSUE THREAD

**Issue by Gab0** [Gab0/japonicus#96]
Cheers! Can anyone with a good rig run this bash script of japonicus runs, then share related logs?
That would have practical purposes on finding good params, also would help me on tweaking genetic algorithm evolutionary parameters. 
Of course theres a chance of crashing, so share tracebacks in case XD
Thanks!
```
#!/bin/bash
#japonicus_run.sh

python3 japonicus.py -gc --strat RSI_BULL_BEAR_ADX --deltaDays 20 --candleSize 10
python3 japonicus.py -gc --strat RSI_BULL_BEAR_ADX --deltaDays 60 --candleSize 10
python3 japonicus.py -gc --strat RSI_BULL_BEAR_ADX --deltaDays 20 --candleSize 5
python3 japonicus.py -gc --strat RSI_BULL_BEAR_ADX --deltaDays 60 --candleSize 5

```
```
Resources:
strategy: https://github.com/Gab0/gekko-adapted-strategies.git
indicators: https://github.com/Gab0/gekko-extra-indicators.git
candles: https://github.com/Gab0/gekko-candlesticks.git
```

**Comment by jthope** [comment]
Gab0, I am running backtests right now using the latest code (and modified strats/indicators). However, I am using mongodb as my database, are you expecting results based on the data from the candle repos you provided?

**Comment by Gab0** [comment]
hey, no... the database provided is optional, any db does good.
It's really hardcoded? Oh no dam bugs I'm checking this later, if it is h.c. I'l commit the fix.
Thanks! go backtesting ^^ cheers

**Comment by jthope** [comment]
python3 japonicus.py -gc --strat RSI_BULL_BEAR_ADX --deltaDays 60 --candleSize 5

Question about the log file -- do I select the last one, or scan through the set for the best profit? With the last one selected, the backtest from Gekko provided a +20.78%, where the overall market was -17%. Not bad results, but the output says *Annual* profit of 136.4% -- which I assume is a prediction based on the output of the 2 months of data the backtest ran on?

[RSI_BULL_BEAR_ADX-binance-USDT-BTC-146035.log](https://github.com/Gab0/japonicus/files/1781972/RSI_BULL_BEAR_ADX-binance-USDT-BTC-146035.log)

Will continue running the others.

**Comment by BradT7** [comment]
I’m currently running these tests for you as well. Does -gc differ from -g in that you can pass it custom variables? If so this is excellent, and handles one of the features requested too. Thanks a lot! 
It looks like it ignores the settings.py variable, and overrides it with the one passed, while pulling in all the other variables not defined. I'll know after this second run is finished, and therefore no apparent bug.

**Comment by Gab0** [comment]
@jthope thanks. Annual profit is 12 random deltaDays periods backtested in sequence. 
Thats good results... may even try it on real trading.

@BradT7 `-gc` is a GA representation mode that is more complex than `-g`... custom variables works the same for both. So we pray for no bugs XD
