### ISSUE TITLE
Dataset not takken into consideration

### ISSUE THREAD

**Issue by deadheadtn** [Gab0/japonicus#98]
Using the new update i can't choose the dataset i want
`The profits reported here are the profit beyond market price change;
	i.e. shown profit =  <backtest profit> - <market profit in evaluated candlestick period>;
Evolving RSI_BULL_BEAR strategy;

evaluated parameters ranges:
SMA_long                      (700.0, 1300.0)
SMA_short                     (35.0, 65.0)
BULL_RSI                      (7.0, 13.0)
BULL_RSI_high                 (56.0, 104.0)
BULL_RSI_low                  (42.0, 78.0)
BEAR_RSI                      (10.5, 19.5)
BEAR_RSI_high                 (35.0, 65.0)
BEAR_RSI_low                  (14.0, 26.0)
{
    "gekkoDebug": true,
    "showIndividualEvaluationInfo": false,
    "parameter_spread": 60,
    "POP_SIZE": 30,
    "NBEPOCH": 800,
    "evaluateSettingsPeriodically": 1.0,
    "deltaDays": 27,
    "ParallelCandlestickDataset": 1,
    "cxpb": 0.6,
    "mutpb": 0.2,
    "_lambda": 7,
    "PRoFIGA_beta": 0.005,
    "ageBoundaries": [
        9,
        19
    ],
    "candleSize": 10,
    "proofSize": 12,
    "DRP": 70,
    "ParallelBacktests": 6,
    "finaltest": {
        "NBBESTINDS": 1,
        "NBADDITIONALINDS": 4
    },
    "chromosome": {
        "GeneSize": 2,
        "Density": 3
    },
    "weights": {
        "profit": 1.0,
        "sharpe": 0.1
    }
}

evolution candlestick dataset 2018-02-05 14:45:00 to 2018-03-05 15:29:00
TRX/BTC @binance

evaluation candlestick dataset 2018-01-28 18:05:00 to 2018-03-02 23:40:00
VEN/BTC @binance
`

It tests on VEN/BTC .

`#!/bin/python
import os
import js2py
from configStrategies import cS
from configIndicators import cI

class _settings:
    def __init__(self, **entries):
        '''
        print(entries)
        def iterate(self, DATA):
            for W in DATA.keys():
                if type(DATA[W]) == dict:
                    iterate(self,DATA[W])
                else:
                    self.__dict__.update(DATA)
        iterate(self,entries)
        '''
        self.__dict__.update(entries)

    def getstrat(self, name):
        return self.strategies[name]

def getSettings(specific=None):
    HOME = os.getenv("HOME")
    s = {
        'Global': {
            'gekkoPath': HOME+'/gekko',
            'configFilename': 'example-config.js',
            'save_dir': "output",
            'log_name': 'evolution_gen.csv',

            # Hosts list of remote machines running gekko, to distribute evaluation load;
            # option values: path to HOSTS file list OR False;
            'RemoteAWS': '../AmazonSetup/hosts',

            # Your gekko local URL - CHECK THIS!
            'GekkoURLs': [ 'http://151.80.146.245:35265' ]
        },
        # genetic algorithm settings
        'generations': {
            # show gekko verbose (strat info) - gekko must start with -d flag;
            'gekkoDebug': True,

            # Verbose single evaluation results;
            'showIndividualEvaluationInfo': False,

            # if parameter is set to value rather than tuple limits at settings, make the value
            # a tuple based on chosen spread value (percents); value: 10 --spread=50-->  value: (5,15)
            'parameter_spread' : 60,

            # Initial population size, per locale
            'POP_SIZE': 30, 

            # number of epochs to run
            'NBEPOCH': 800,

            # show current best settings on every X epochs. (or False)
            'evaluateSettingsPeriodically': 20,

            # time window size on days of candlesticks for each evaluation
            'deltaDays': 27,

            # Number of candlestick data loaded simultaneously in each locale;
            # slower EPOCHS, theoretical better evolution;
            # seems broken. values other than 1 makes evolution worse.
            'ParallelCandlestickDataset': 1,

            # -- Genetic Algorithm Parameters
            'cxpb': 0.6, # Probabilty of crossover 
            'mutpb': 0.2,# Probability of mutation;
            '_lambda': 7,# size of offspring generated per epoch;

            'PRoFIGA_beta': 0.005, # weight of PRoFIGA calculations on variability of population size
            'ageBoundaries': (9, 19), # minimum age to die, age when everyone dies (on EPOCHS)

            'candleSize': 10, # candle size for gekko backtest, in minutes

            'proofSize': 12,

            'DRP': 70,# Date range persistence; Number of subsequent rounds
             # until another time range in dataset is selected;
            'ParallelBacktests': 6,

            'finaltest': {
                'NBBESTINDS': 1,
                'NBADDITIONALINDS': 4,
            },
            'chromosome': {
                'GeneSize': 2,
                'Density': 3,
            },
            'weights': {
                'profit': 1.0,
                'sharpe': 0.1}
        },

        # bayesian optimization settings
        'bayesian': {
            # show gekko verbose (strat info) - gekko must start with -d flag;
            'gekkoDebug': False,

            # time window size on days of candlesticks for each evaluation
            'deltaDays': 60,

            # number of evaluation rounds
            'num_rounds': 10,

            # seed for randomziation of values
            'random_state': 2017,

            # number of iterations on each round
            'num_iter': 50,

            # number of random values to start bayes evaluation
            'init_points': 9,

            'parallel': False,
            'show_chart': False,
            'save': True,
            
            'parameter_spread': 100,

            # candleSize & historySize on Gekko, for all evals
            'candleSize': 30,
            'historySize': 10,

            'watch':{
                "exchange": "poloniex",
                "currency": 'USDT',
                "asset": 'BTC'
            }
        },
        'dataset' : {
            # -- Gekko Dataset Settings
            # leave the ! on the ignored entry as convenient;

             # dataset_source can be set to None so it searches from any source;
            'dataset_source': { # in case of specifying exchange-currency-asset, rename this removing the '!', and del the original key above.
                "exchange": "binance",
                "currency": 'BTC',
                "asset": 'TRX',
            },
            'eval_dataset_source': None,

            # span in days from the end of dataset to the beggining. Or zero.
            # (to restrain length);
            'dataset_span': 0,
            'eval_dataset_span': 0

            },
        'strategies': cS,
        'indicators': cI,
        'skeletons': {
            'ontrend': {
                "SMA_long": 1000,
                "SMA_short": 50
            }
        }
    }

    if specific != None:
        if not specific:
            return _settings(**s)
        else:
            return _settings(**s[specific])

    return s

def get_configjs(filename="example-config.js"):
    with open(filename, "r") as f:
        text = f.read()
    text = text.replace("module.exports = config;","config;")
    return js2py.eval_js(text).to_dict()
`

**Comment by Gab0** [comment]
At your Settings.py:
```
 'dataset_source': {
            "exchange": "binance",
            "currency": 'BTC',
            "asset": 'TRX',
        },
```
Then at the program output:
```
evolution candlestick dataset 2018-02-05 14:45:00 to 2018-03-05 15:29:00
TRX/BTC @binance
```
It seems all good..

**Comment by deadheadtn** [comment]
Yes it's displayed but it's running the second dataset
`evaluation candlestick dataset 2018-01-28 18:05:00 to 2018-03-02 23:40:00
VEN/BTC @binance`
i had to delete all the datasets in the database to access `TRX/BTC @binance`

**Comment by BradT7** [comment]
This looks to be related to my question a few days ago [#92](https://github.com/Gab0/japonicus/issues/92), in which Gab explained the difference between evolution and evaluation. It's confusing I know, but back testing the results seem to imply it's just looking at the evolution pairing as intended.

**Comment by Gab0** [comment]
Oh, so its confusing you say :'( lool ok I will make things more clear from the interface ^^
