### ISSUE TITLE
New Strategy

### ISSUE THREAD

**Issue by BradT7** [Gab0/japonicus#99]
Hello, I've found this promising strategy [StochRSI_MACD_BB](https://gist.github.com/John1231983/0822062d6e252dda82e1759bb47ef4fb), but it never seems to trade. Has there been an update in gekko perhaps that broke it, what's weird is it doesn't seem to error out, just no trades.
Perhaps someone else smarter at coding than me can assist. I already ran it through japonicus, but it still comes out with no trades no matter what the variables. If we're able to figure this out, japonicus could make this a real winner, I'll keep studying it over for now.

**Comment by Gab0** [comment]
Hey.. MACD is not a good indicator, it heavly fluctuates from price to price, market to market... better use PPO that has same purpose but is benign. Search about that on google... that may be the problem with the strat, try to swap these indicators. cheers!
